name: test opencv build on windows

on: push

jobs:
  run-ci:
    runs-on: windows-2025
    steps:
    - name: Checkout Forked OpenCV
      uses: actions/checkout@v4
      with:
        repository: 'habib-source/opencv'
        ref: 'FindPythonmanual'
    - name: install numpy
      run: python3 -m pip install numpy
    - name: Run OpenCV CMake Configuration
      run: cmake -B build -DBUILD_opencv_python3=ON -DBUILD_opencv_python2=OFF -DBUILD_opencv_java=OFF -DINSTALL_CREATE_DISTRIB=ON -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF -DPython3_LIMITED_API=ON -DBUILD_OPENEXR=ON
